# Generated by Django 2.2.8 on 2020-09-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item2',
            new_name='Item',
        ),
    ]
